package com.example.zq.play_android.data.source.local;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.zq.play_android.bean.Carousel;

import com.example.zq.play_android.data.source.local.CarouselDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig carouselDaoConfig;

    private final CarouselDao carouselDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        carouselDaoConfig = daoConfigMap.get(CarouselDao.class).clone();
        carouselDaoConfig.initIdentityScope(type);

        carouselDao = new CarouselDao(carouselDaoConfig, this);

        registerDao(Carousel.class, carouselDao);
    }
    
    public void clear() {
        carouselDaoConfig.getIdentityScope().clear();
    }

    public CarouselDao getCarouselDao() {
        return carouselDao;
    }

}
